<?php

namespace ContainerSjxPRe5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirectToPreviousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RedirectToPrevious' shared autowired service.
     *
     * @return \App\Service\RedirectToPrevious
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\src\\Service\\RedirectToPrevious.php';

        return $container->privates['App\\Service\\RedirectToPrevious'] = new \App\Service\RedirectToPrevious(($container->services['session'] ?? $container->load('getSessionService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
