<?php

namespace ContainerSD0a2DQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRandomControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RandomController' shared autowired service.
     *
     * @return \App\Controller\RandomController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\PhotoController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\RandomController.php';

        $container->services['App\\Controller\\RandomController'] = $instance = new \App\Controller\RandomController(($container->services['session'] ?? $container->load('getSessionService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\RandomController', $container));

        return $instance;
    }
}
